# Data Processing


### Importing libraies

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

###Importing the dataset

In [9]:
dataset = pd.read_csv('Dataset_master.xlsx - American Express User Exit Pred.csv')
X = dataset.iloc[:, 0:-1].values
Y = dataset.iloc[:, -1].values

### Encoding Catagorical Data

####LabelEncoding - Dependent Variable (Gender Column)

In [10]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

#### OneHotEncoding - Independent Variable (Geography Column)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Spliting the data into testset and traing set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.2 , random_state = 0)

In [14]:
print(Y_train)

[0 0 0 ... 1 1 0]


###Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

##ANN Implimentation


###Initialisation

In [16]:
ann = tf.keras.models.Sequential()

###Adding Input Layer & first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

###Adding Second Hidden Layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

###Adding Output Layer

In [19]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

###ANN Training

###Compiling ANN

In [20]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

### Training on Training Dataset

In [21]:
print(X_train)

[[ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
   0.34018176]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.67326188]
 ...
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
  -0.17067658]
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.4232319 ]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -1.67963883]]


In [22]:
ann.fit(X_train,Y_train,batch_size=32,epochs=120)

Epoch 1/120
249/249 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7524
Epoch 2/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4623 - accuracy: 0.7947
Epoch 3/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4463 - accuracy: 0.7971
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4363 - accuracy: 0.8029
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 0.8096
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8139
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4194 - accuracy: 0.8160
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.8166
Epoch 9/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8172
Epoch 10/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4101 - accura

## Predictions

###Single Prediction

In [23]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 211ms/step
[[False]]


###Prediction on testset

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))

63/63 [==============================] - 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


###Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1496   77]
 [ 246  167]]


0.8373615307150051